# Generated by Django 6.0.3 on 2026-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='order_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
