# Generated by Django 6.0.3 on 2026-03-20 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_company_order_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('text', models.TextField(blank=True, verbose_name='Опис')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('type', models.CharField(choices=[('income', 'Прибуток'), ('expense', 'Витрата')], max_length=10, verbose_name='Тип')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.company')),
            ],
        ),
    ]
