# Generated by Django 6.0.3 on 2026-03-20 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('main', '0002_company_order_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
    ]
