# Generated by Django 6.0.3 on 2026-03-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг'), ('l', 'л')], default='pcs', max_length=20, verbose_name='Одиниця виміру')),
            ],
        ),
    ]
