# Generated by Django 6.0.3 on 2026-03-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_company_order_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ клієнта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон клієнта')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('default_address', models.TextField(blank=True, verbose_name='Адреса за замовчуванням')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='main.company')),
            ],
            options={
                'ordering': ['full_name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'full_name', 'phone'), name='unique_client_per_company_name_phone')],
            },
        ),
    ]
