# Generated by Django 6.0.3 on 2026-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company_order_counter'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='local_id',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Внутрішній id'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('company', 'local_id'), name='unique_order_number_per_company'),
        ),
    ]
