# Generated by Django 6.0.3 on 2026-03-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company_order_counter'),
        ('order', '0003_remove_order_unique_order_number_per_company_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_order_number_per_company',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('company', 'local_id'), name='unique_order_number_per_company'),
        ),
    ]
