# Generated by Django 6.0.3 on 2026-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_total_alter_order_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовивіз'), ('courier', "Кур'єр"), ('post', 'Пошта')], default='pickup', max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Карта'), ('cash', 'Готівка')], default=1, max_length=20, verbose_name='Спосіб оплати'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='post_service',
            field=models.CharField(blank=True, choices=[('ukrpost', 'Украпошта'), ('nova_poshta', 'Нова пошта')], max_length=50, verbose_name='Служба доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Очікує комплектування'), ('packing', 'Комплектується'), ('packed', 'Сформовано'), ('delivery', 'В дорозі'), ('completed', 'Завершено')], default='waiting', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна сума'),
        ),
    ]
