# Generated by Django 6.0.3 on 2026-03-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('order', '0008_order_customer_name_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='client.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_service',
            field=models.CharField(blank=True, choices=[('ukrpost', 'Укрпошта'), ('nova_poshta', 'Нова пошта')], max_length=50, verbose_name='Служба доставки'),
        ),
    ]
